"""Add models from json.

Revision ID: 3d419d417967
Revises: 2c47c3eafc61
Create Date: 2020-07-22 19:21:47.009945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d419d417967'
down_revision = '2c47c3eafc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Elements',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Count', sa.Integer(), nullable=False),
    sa.Column('ElementType_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ElementType_Id'], ['ElementTypes.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ParameterValues',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Value', sa.Float(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['Parameters.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ElementParameterValue',
    sa.Column('ElementId', sa.Integer(), nullable=False),
    sa.Column('ParameterValueId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ElementId'], ['Elements.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ParameterValueId'], ['ParameterValues.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ElementId', 'ParameterValueId')
    )
    op.create_index(op.f('ix_ElementParameterValue_ElementId'), 'ElementParameterValue', ['ElementId'], unique=False)
    op.create_index(op.f('ix_ElementParameterValue_ParameterValueId'), 'ElementParameterValue', ['ParameterValueId'], unique=False)
    op.create_table('Rooms',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Unicode(), nullable=False),
    sa.Column('Factor', sa.Integer(), nullable=False),
    sa.Column('SalaryFactor', sa.Integer(), nullable=False),
    sa.Column('RoomReportSalary', sa.Integer(), nullable=True),
    sa.Column('RoomType_Id', sa.Integer(), nullable=False),
    sa.Column('Document_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Document_Id'], ['Documents.Id'], ),
    sa.ForeignKeyConstraint(['RoomType_Id'], ['RoomTypes.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('RoomElement',
    sa.Column('Room_Id', sa.Integer(), nullable=False),
    sa.Column('Element_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Element_Id'], ['Elements.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Room_Id'], ['Rooms.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Room_Id', 'Element_Id')
    )
    op.create_index(op.f('ix_RoomElement_Element_Id'), 'RoomElement', ['Element_Id'], unique=False)
    op.create_index(op.f('ix_RoomElement_Room_Id'), 'RoomElement', ['Room_Id'], unique=False)
    op.create_table('RoomParameterValue',
    sa.Column('RoomId', sa.Integer(), nullable=False),
    sa.Column('ParameterValueId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ParameterValueId'], ['ParameterValues.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['RoomId'], ['Rooms.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('RoomId', 'ParameterValueId')
    )
    op.create_index(op.f('ix_RoomParameterValue_ParameterValueId'), 'RoomParameterValue', ['ParameterValueId'], unique=False)
    op.create_index(op.f('ix_RoomParameterValue_RoomId'), 'RoomParameterValue', ['RoomId'], unique=False)
    op.create_table('Works',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IsVolumeManual', sa.Boolean(), nullable=False),
    sa.Column('Volume', sa.Float(), nullable=False),
    sa.Column('Worker', sa.Unicode(), nullable=True),
    sa.Column('ReportSalarySum', sa.Float(), nullable=False),
    sa.Column('ReportSalary', sa.Float(), nullable=False),
    sa.Column('IsPriceManual', sa.Boolean(), nullable=False),
    sa.Column('PriceValue', sa.Float(), nullable=False),
    sa.Column('WorkType_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['WorkType_Id'], ['WorkTypes.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('RoomWork',
    sa.Column('Room_Id', sa.Integer(), nullable=False),
    sa.Column('Work_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Room_Id'], ['Rooms.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Work_Id'], ['Works.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Room_Id', 'Work_Id')
    )
    op.create_index(op.f('ix_RoomWork_Room_Id'), 'RoomWork', ['Room_Id'], unique=False)
    op.create_index(op.f('ix_RoomWork_Work_Id'), 'RoomWork', ['Work_Id'], unique=False)
    op.create_table('WorkParameterValue',
    sa.Column('WorkId', sa.Integer(), nullable=False),
    sa.Column('ParameterValueId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ParameterValueId'], ['ParameterValues.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['WorkId'], ['Works.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('WorkId', 'ParameterValueId')
    )
    op.create_index(op.f('ix_WorkParameterValue_ParameterValueId'), 'WorkParameterValue', ['ParameterValueId'], unique=False)
    op.create_index(op.f('ix_WorkParameterValue_WorkId'), 'WorkParameterValue', ['WorkId'], unique=False)
    op.create_index(op.f('ix_Categories_Parent_Id'), 'Categories', ['Parent_Id'], unique=False)
    op.drop_index('IX_Category_Parent_Id', table_name='Categories')
    op.add_column('Documents', sa.Column('Address', sa.Unicode(), nullable=True))
    op.alter_column('Documents', 'Json',
               existing_type=sa.NVARCHAR(),
               nullable=False)
    op.alter_column('Documents', 'Name',
               existing_type=sa.NVARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_Documents_MultiProject_Id'), 'Documents', ['MultiProject_Id'], unique=False)
    op.drop_index('IX_Document_MultiProject_Id', table_name='Documents')
    op.create_index(op.f('ix_Formulae_ElementType_Id'), 'Formulae', ['ElementType_Id'], unique=False)
    op.create_index(op.f('ix_Formulae_RoomType_Id'), 'Formulae', ['RoomType_Id'], unique=False)
    op.drop_index('IX_Formula_ElementType_Id', table_name='Formulae')
    op.drop_index('IX_Formula_RoomType_Id', table_name='Formulae')
    op.create_index(op.f('ix_MaterialTypes_Formula_Id'), 'MaterialTypes', ['Formula_Id'], unique=False)
    op.create_index(op.f('ix_MaterialTypes_WorkType_Id'), 'MaterialTypes', ['WorkType_Id'], unique=False)
    op.drop_index('IX_MaterialType_Formula_Id', table_name='MaterialTypes')
    op.drop_index('IX_MaterialType_WorkType_Id', table_name='MaterialTypes')
    op.create_index(op.f('ix_ParameterFormulas_Formula_Id'), 'ParameterFormulas', ['Formula_Id'], unique=False)
    op.create_index(op.f('ix_ParameterFormulas_Parameter_Id'), 'ParameterFormulas', ['Parameter_Id'], unique=False)
    op.drop_index('IX_ParameterFormula_Formula_Id', table_name='ParameterFormulas')
    op.drop_index('IX_ParameterFormula_Parameter_Id', table_name='ParameterFormulas')
    op.create_index(op.f('ix_TagWorkTypes_Tag_Id'), 'TagWorkTypes', ['Tag_Id'], unique=False)
    op.create_index(op.f('ix_TagWorkTypes_WorkType_Id'), 'TagWorkTypes', ['WorkType_Id'], unique=False)
    op.drop_index('IX_TagWorkType_Tag_Id', table_name='TagWorkTypes')
    op.drop_index('IX_TagWorkType_WorkType_Id', table_name='TagWorkTypes')
    op.create_index(op.f('ix_TemplateBlocks_Template_Id'), 'TemplateBlocks', ['Template_Id'], unique=False)
    op.drop_index('IX_TemplateBlock_Template_Id', table_name='TemplateBlocks')
    op.create_index(op.f('ix_WorkTypeCategories_Category_Id'), 'WorkTypeCategories', ['Category_Id'], unique=False)
    op.create_index(op.f('ix_WorkTypeCategories_WorkType_Id'), 'WorkTypeCategories', ['WorkType_Id'], unique=False)
    op.drop_index('IX_WorkTypeCategory_Category_Id', table_name='WorkTypeCategories')
    op.drop_index('IX_WorkTypeCategory_WorkType_Id', table_name='WorkTypeCategories')
    op.create_index(op.f('ix_WorkTypes_Formula_Id'), 'WorkTypes', ['Formula_Id'], unique=False)
    op.drop_index('IX_WorkType_Formula_Id', table_name='WorkTypes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('IX_WorkType_Formula_Id', 'WorkTypes', ['Formula_Id'], unique=False)
    op.drop_index(op.f('ix_WorkTypes_Formula_Id'), table_name='WorkTypes')
    op.create_index('IX_WorkTypeCategory_WorkType_Id', 'WorkTypeCategories', ['WorkType_Id'], unique=False)
    op.create_index('IX_WorkTypeCategory_Category_Id', 'WorkTypeCategories', ['Category_Id'], unique=False)
    op.drop_index(op.f('ix_WorkTypeCategories_WorkType_Id'), table_name='WorkTypeCategories')
    op.drop_index(op.f('ix_WorkTypeCategories_Category_Id'), table_name='WorkTypeCategories')
    op.create_index('IX_TemplateBlock_Template_Id', 'TemplateBlocks', ['Template_Id'], unique=False)
    op.drop_index(op.f('ix_TemplateBlocks_Template_Id'), table_name='TemplateBlocks')
    op.create_index('IX_TagWorkType_WorkType_Id', 'TagWorkTypes', ['WorkType_Id'], unique=False)
    op.create_index('IX_TagWorkType_Tag_Id', 'TagWorkTypes', ['Tag_Id'], unique=False)
    op.drop_index(op.f('ix_TagWorkTypes_WorkType_Id'), table_name='TagWorkTypes')
    op.drop_index(op.f('ix_TagWorkTypes_Tag_Id'), table_name='TagWorkTypes')
    op.create_index('IX_ParameterFormula_Parameter_Id', 'ParameterFormulas', ['Parameter_Id'], unique=False)
    op.create_index('IX_ParameterFormula_Formula_Id', 'ParameterFormulas', ['Formula_Id'], unique=False)
    op.drop_index(op.f('ix_ParameterFormulas_Parameter_Id'), table_name='ParameterFormulas')
    op.drop_index(op.f('ix_ParameterFormulas_Formula_Id'), table_name='ParameterFormulas')
    op.create_index('IX_MaterialType_WorkType_Id', 'MaterialTypes', ['WorkType_Id'], unique=False)
    op.create_index('IX_MaterialType_Formula_Id', 'MaterialTypes', ['Formula_Id'], unique=False)
    op.drop_index(op.f('ix_MaterialTypes_WorkType_Id'), table_name='MaterialTypes')
    op.drop_index(op.f('ix_MaterialTypes_Formula_Id'), table_name='MaterialTypes')
    op.create_index('IX_Formula_RoomType_Id', 'Formulae', ['RoomType_Id'], unique=False)
    op.create_index('IX_Formula_ElementType_Id', 'Formulae', ['ElementType_Id'], unique=False)
    op.drop_index(op.f('ix_Formulae_RoomType_Id'), table_name='Formulae')
    op.drop_index(op.f('ix_Formulae_ElementType_Id'), table_name='Formulae')
    op.create_index('IX_Document_MultiProject_Id', 'Documents', ['MultiProject_Id'], unique=False)
    op.drop_index(op.f('ix_Documents_MultiProject_Id'), table_name='Documents')
    op.alter_column('Documents', 'Name',
               existing_type=sa.NVARCHAR(),
               nullable=True)
    op.alter_column('Documents', 'Json',
               existing_type=sa.NVARCHAR(),
               nullable=True)
    op.drop_column('Documents', 'Address')
    op.create_index('IX_Category_Parent_Id', 'Categories', ['Parent_Id'], unique=False)
    op.drop_index(op.f('ix_Categories_Parent_Id'), table_name='Categories')
    op.drop_index(op.f('ix_WorkParameterValue_WorkId'), table_name='WorkParameterValue')
    op.drop_index(op.f('ix_WorkParameterValue_ParameterValueId'), table_name='WorkParameterValue')
    op.drop_table('WorkParameterValue')
    op.drop_index(op.f('ix_RoomWork_Work_Id'), table_name='RoomWork')
    op.drop_index(op.f('ix_RoomWork_Room_Id'), table_name='RoomWork')
    op.drop_table('RoomWork')
    op.drop_table('Works')
    op.drop_index(op.f('ix_RoomParameterValue_RoomId'), table_name='RoomParameterValue')
    op.drop_index(op.f('ix_RoomParameterValue_ParameterValueId'), table_name='RoomParameterValue')
    op.drop_table('RoomParameterValue')
    op.drop_index(op.f('ix_RoomElement_Room_Id'), table_name='RoomElement')
    op.drop_index(op.f('ix_RoomElement_Element_Id'), table_name='RoomElement')
    op.drop_table('RoomElement')
    op.drop_table('Rooms')
    op.drop_index(op.f('ix_ElementParameterValue_ParameterValueId'), table_name='ElementParameterValue')
    op.drop_index(op.f('ix_ElementParameterValue_ElementId'), table_name='ElementParameterValue')
    op.drop_table('ElementParameterValue')
    op.drop_table('ParameterValues')
    op.drop_table('Elements')
    # ### end Alembic commands ###
