"""Add models from json.

Revision ID: c54ff6fc0d07
Revises: 2c47c3eafc61
Create Date: 2020-07-23 15:27:41.378259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54ff6fc0d07'
down_revision = '2c47c3eafc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ParameterWithValues',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Value', sa.Float(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['Parameters.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Rooms',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Unicode(), nullable=False),
    sa.Column('Factor', sa.Integer(), nullable=False),
    sa.Column('SalaryFactor', sa.Integer(), nullable=False),
    sa.Column('RoomReportSalary', sa.Integer(), nullable=True),
    sa.Column('RoomType_Id', sa.Integer(), nullable=True),
    sa.Column('Document_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Document_Id'], ['Documents.Id'], ),
    sa.ForeignKeyConstraint(['RoomType_Id'], ['RoomTypes.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Elements',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Count', sa.Integer(), nullable=False),
    sa.Column('ElementType_Id', sa.Integer(), nullable=False),
    sa.Column('Room_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ElementType_Id'], ['ElementTypes.Id'], ),
    sa.ForeignKeyConstraint(['Room_Id'], ['Rooms.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ParameterWithValueRooms',
    sa.Column('ParameterWithValue_Id', sa.Integer(), nullable=False),
    sa.Column('Room_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ParameterWithValue_Id'], ['ParameterWithValues.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Room_Id'], ['Rooms.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ParameterWithValue_Id', 'Room_Id')
    )
    op.create_index(op.f('ix_ParameterWithValueRooms_ParameterWithValue_Id'), 'ParameterWithValueRooms', ['ParameterWithValue_Id'], unique=False)
    op.create_index(op.f('ix_ParameterWithValueRooms_Room_Id'), 'ParameterWithValueRooms', ['Room_Id'], unique=False)
    op.create_table('Works',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('IsVolumeManual', sa.Boolean(), nullable=False),
    sa.Column('Volume', sa.Float(), nullable=False),
    sa.Column('Worker', sa.Unicode(), nullable=True),
    sa.Column('ReportSalarySum', sa.Float(), nullable=False),
    sa.Column('ReportSalary', sa.Float(), nullable=False),
    sa.Column('IsPriceManual', sa.Boolean(), nullable=False),
    sa.Column('PriceValue', sa.Float(), nullable=False),
    sa.Column('WorkType_Id', sa.Integer(), nullable=False),
    sa.Column('Room_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Room_Id'], ['Rooms.Id'], ),
    sa.ForeignKeyConstraint(['WorkType_Id'], ['WorkTypes.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ParameterWithValueElements',
    sa.Column('ParameterWithValue_Id', sa.Integer(), nullable=False),
    sa.Column('Element_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Element_Id'], ['Elements.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ParameterWithValue_Id'], ['ParameterWithValues.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ParameterWithValue_Id', 'Element_Id')
    )
    op.create_index(op.f('ix_ParameterWithValueElements_Element_Id'), 'ParameterWithValueElements', ['Element_Id'], unique=False)
    op.create_index(op.f('ix_ParameterWithValueElements_ParameterWithValue_Id'), 'ParameterWithValueElements', ['ParameterWithValue_Id'], unique=False)
    op.create_table('WorkParameterWithValues',
    sa.Column('Work_Id', sa.Integer(), nullable=False),
    sa.Column('ParameterWithValue_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ParameterWithValue_Id'], ['ParameterWithValues.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Work_Id'], ['Works.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Work_Id', 'ParameterWithValue_Id')
    )
    op.create_index(op.f('ix_WorkParameterWithValues_ParameterWithValue_Id'), 'WorkParameterWithValues', ['ParameterWithValue_Id'], unique=False)
    op.create_index(op.f('ix_WorkParameterWithValues_Work_Id'), 'WorkParameterWithValues', ['Work_Id'], unique=False)
    op.create_index(op.f('ix_Categories_Parent_Id'), 'Categories', ['Parent_Id'], unique=False)
    op.drop_index('IX_Category_Parent_Id', table_name='Categories')
    op.add_column('Documents', sa.Column('Address', sa.Unicode(), nullable=True))
    op.alter_column('Documents', 'Json',
               existing_type=sa.NVARCHAR(),
               nullable=False)
    op.alter_column('Documents', 'Name',
               existing_type=sa.NVARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_Documents_MultiProject_Id'), 'Documents', ['MultiProject_Id'], unique=False)
    op.drop_index('IX_Document_MultiProject_Id', table_name='Documents')
    op.create_index(op.f('ix_Formulae_ElementType_Id'), 'Formulae', ['ElementType_Id'], unique=False)
    op.create_index(op.f('ix_Formulae_RoomType_Id'), 'Formulae', ['RoomType_Id'], unique=False)
    op.drop_index('IX_Formula_ElementType_Id', table_name='Formulae')
    op.drop_index('IX_Formula_RoomType_Id', table_name='Formulae')
    op.create_index(op.f('ix_MaterialTypes_Formula_Id'), 'MaterialTypes', ['Formula_Id'], unique=False)
    op.create_index(op.f('ix_MaterialTypes_WorkType_Id'), 'MaterialTypes', ['WorkType_Id'], unique=False)
    op.drop_index('IX_MaterialType_Formula_Id', table_name='MaterialTypes')
    op.drop_index('IX_MaterialType_WorkType_Id', table_name='MaterialTypes')
    op.create_index(op.f('ix_ParameterFormulas_Formula_Id'), 'ParameterFormulas', ['Formula_Id'], unique=False)
    op.create_index(op.f('ix_ParameterFormulas_Parameter_Id'), 'ParameterFormulas', ['Parameter_Id'], unique=False)
    op.drop_index('IX_ParameterFormula_Formula_Id', table_name='ParameterFormulas')
    op.drop_index('IX_ParameterFormula_Parameter_Id', table_name='ParameterFormulas')
    op.create_index(op.f('ix_TagWorkTypes_Tag_Id'), 'TagWorkTypes', ['Tag_Id'], unique=False)
    op.create_index(op.f('ix_TagWorkTypes_WorkType_Id'), 'TagWorkTypes', ['WorkType_Id'], unique=False)
    op.drop_index('IX_TagWorkType_Tag_Id', table_name='TagWorkTypes')
    op.drop_index('IX_TagWorkType_WorkType_Id', table_name='TagWorkTypes')
    op.create_index(op.f('ix_TemplateBlocks_Template_Id'), 'TemplateBlocks', ['Template_Id'], unique=False)
    op.drop_index('IX_TemplateBlock_Template_Id', table_name='TemplateBlocks')
    op.create_index(op.f('ix_WorkTypeCategories_Category_Id'), 'WorkTypeCategories', ['Category_Id'], unique=False)
    op.create_index(op.f('ix_WorkTypeCategories_WorkType_Id'), 'WorkTypeCategories', ['WorkType_Id'], unique=False)
    op.drop_index('IX_WorkTypeCategory_Category_Id', table_name='WorkTypeCategories')
    op.drop_index('IX_WorkTypeCategory_WorkType_Id', table_name='WorkTypeCategories')
    op.create_index(op.f('ix_WorkTypes_Formula_Id'), 'WorkTypes', ['Formula_Id'], unique=False)
    op.drop_index('IX_WorkType_Formula_Id', table_name='WorkTypes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('IX_WorkType_Formula_Id', 'WorkTypes', ['Formula_Id'], unique=False)
    op.drop_index(op.f('ix_WorkTypes_Formula_Id'), table_name='WorkTypes')
    op.create_index('IX_WorkTypeCategory_WorkType_Id', 'WorkTypeCategories', ['WorkType_Id'], unique=False)
    op.create_index('IX_WorkTypeCategory_Category_Id', 'WorkTypeCategories', ['Category_Id'], unique=False)
    op.drop_index(op.f('ix_WorkTypeCategories_WorkType_Id'), table_name='WorkTypeCategories')
    op.drop_index(op.f('ix_WorkTypeCategories_Category_Id'), table_name='WorkTypeCategories')
    op.create_index('IX_TemplateBlock_Template_Id', 'TemplateBlocks', ['Template_Id'], unique=False)
    op.drop_index(op.f('ix_TemplateBlocks_Template_Id'), table_name='TemplateBlocks')
    op.create_index('IX_TagWorkType_WorkType_Id', 'TagWorkTypes', ['WorkType_Id'], unique=False)
    op.create_index('IX_TagWorkType_Tag_Id', 'TagWorkTypes', ['Tag_Id'], unique=False)
    op.drop_index(op.f('ix_TagWorkTypes_WorkType_Id'), table_name='TagWorkTypes')
    op.drop_index(op.f('ix_TagWorkTypes_Tag_Id'), table_name='TagWorkTypes')
    op.create_index('IX_ParameterFormula_Parameter_Id', 'ParameterFormulas', ['Parameter_Id'], unique=False)
    op.create_index('IX_ParameterFormula_Formula_Id', 'ParameterFormulas', ['Formula_Id'], unique=False)
    op.drop_index(op.f('ix_ParameterFormulas_Parameter_Id'), table_name='ParameterFormulas')
    op.drop_index(op.f('ix_ParameterFormulas_Formula_Id'), table_name='ParameterFormulas')
    op.create_index('IX_MaterialType_WorkType_Id', 'MaterialTypes', ['WorkType_Id'], unique=False)
    op.create_index('IX_MaterialType_Formula_Id', 'MaterialTypes', ['Formula_Id'], unique=False)
    op.drop_index(op.f('ix_MaterialTypes_WorkType_Id'), table_name='MaterialTypes')
    op.drop_index(op.f('ix_MaterialTypes_Formula_Id'), table_name='MaterialTypes')
    op.create_index('IX_Formula_RoomType_Id', 'Formulae', ['RoomType_Id'], unique=False)
    op.create_index('IX_Formula_ElementType_Id', 'Formulae', ['ElementType_Id'], unique=False)
    op.drop_index(op.f('ix_Formulae_RoomType_Id'), table_name='Formulae')
    op.drop_index(op.f('ix_Formulae_ElementType_Id'), table_name='Formulae')
    op.create_index('IX_Document_MultiProject_Id', 'Documents', ['MultiProject_Id'], unique=False)
    op.drop_index(op.f('ix_Documents_MultiProject_Id'), table_name='Documents')
    op.alter_column('Documents', 'Name',
               existing_type=sa.NVARCHAR(),
               nullable=True)
    op.alter_column('Documents', 'Json',
               existing_type=sa.NVARCHAR(),
               nullable=True)
    op.drop_column('Documents', 'Address')
    op.create_index('IX_Category_Parent_Id', 'Categories', ['Parent_Id'], unique=False)
    op.drop_index(op.f('ix_Categories_Parent_Id'), table_name='Categories')
    op.drop_index(op.f('ix_WorkParameterWithValues_Work_Id'), table_name='WorkParameterWithValues')
    op.drop_index(op.f('ix_WorkParameterWithValues_ParameterWithValue_Id'), table_name='WorkParameterWithValues')
    op.drop_table('WorkParameterWithValues')
    op.drop_index(op.f('ix_ParameterWithValueElements_ParameterWithValue_Id'), table_name='ParameterWithValueElements')
    op.drop_index(op.f('ix_ParameterWithValueElements_Element_Id'), table_name='ParameterWithValueElements')
    op.drop_table('ParameterWithValueElements')
    op.drop_table('Works')
    op.drop_index(op.f('ix_ParameterWithValueRooms_Room_Id'), table_name='ParameterWithValueRooms')
    op.drop_index(op.f('ix_ParameterWithValueRooms_ParameterWithValue_Id'), table_name='ParameterWithValueRooms')
    op.drop_table('ParameterWithValueRooms')
    op.drop_table('Elements')
    op.drop_table('Rooms')
    op.drop_table('ParameterWithValues')
    # ### end Alembic commands ###
